In [3]:
import requests
import pandas as pd

In [8]:
url="https://stephen-king-api.onrender.com/api/books"
json_data=requests.get(url).json()
print(json_data)
df=pd.json_normalize(json_data["data"])
df

{'data': [{'id': 1, 'Year': 1974, 'Title': 'Carrie', 'handle': 'carrie', 'Publisher': 'Doubleday', 'ISBN': '978-0-385-08695-0', 'Pages': 199, 'Notes': [''], 'created_at': '2023-11-13T23:48:47.848Z', 'villains': [{'name': 'Tina Blake', 'url': 'https://stephen-king-api.onrender.com/api/villain/4'}, {'name': 'Cindi', 'url': 'https://stephen-king-api.onrender.com/api/villain/14'}, {'name': 'Myra Crewes', 'url': 'https://stephen-king-api.onrender.com/api/villain/16'}, {'name': 'Billy deLois', 'url': 'https://stephen-king-api.onrender.com/api/villain/25'}, {'name': 'Kenny Garson', 'url': 'https://stephen-king-api.onrender.com/api/villain/38'}, {'name': 'Mary Lila Grace', 'url': 'https://stephen-king-api.onrender.com/api/villain/44'}, {'name': 'Christine Hargensen', 'url': 'https://stephen-king-api.onrender.com/api/villain/49'}, {'name': 'Vic Mooney', 'url': 'https://stephen-king-api.onrender.com/api/villain/75'}, {'name': 'The Mortimer Snerds', 'url': 'https://stephen-king-api.onrender.com/api/villain/77'}, {'name': 'Billy Nolan', 'url': 'https://stephen-king-api.onrender.com/api/villain/80'}, {'name': 'Elenor Richmond', 'url': 'https://stephen-king-api.onrender.com/api/villain/90'}, {'name': 'Rachel Spies', 'url': 'https://stephen-king-api.onrender.com/api/villain/94'}, {'name': 'Jackie Talbot', 'url': 'https://stephen-king-api.onrender.com/api/villain/99'}, {'name': 'Donna and Mary Lila Grace Thibodeau', 'url': 'https://stephen-king-api.onrender.com/api/villain/102'}, {'name': 'Jessica Upshaw', 'url': 'https://stephen-king-api.onrender.com/api/villain/108'}, {'name': 'Norma Watson', 'url': 'https://stephen-king-api.onrender.com/api/villain/109'}, {'name': 'Margaret White', 'url': 'https://stephen-king-api.onrender.com/api/villain/113'}]}, {'id': 2, 'Year': 1975, 'Title': "Salem's Lot", 'handle': 'salem-s-lot', 'Publisher': 'Doubleday', 'ISBN': '978-0-385-00751-1', 'Pages': 439, 'Notes': ['Nominee, World Fantasy Award, 1976[2]'], 'created_at': '2023-11-13T23:48:48.098Z', 'villains': [{'name': 'Kurt Barlow', 'url': 'https://stephen-king-api.onrender.com/api/villain/2'}, {'name': 'Richard Straker', 'url': 'https://stephen-king-api.onrender.com/api/villain/98'}]}, {'id': 3, 'Year': 1977, 'Title': 'The Shining', 'handle': 'the-shining', 'Publisher': 'Doubleday', 'ISBN': '978-0-385-12167-5', 'Pages': 447, 'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1978[2]'], 'created_at': '2023-11-13T23:48:48.219Z', 'villains': [{'name': 'Horace M. Derwent', 'url': 'https://stephen-king-api.onrender.com/api/villain/26'}, {'name': 'Delbert Grady', 'url': 'https://stephen-king-api.onrender.com/api/villain/45'}, {'name': 'Jack Torrance', 'url': 'https://stephen-king-api.onrender.com/api/villain/106'}]}, {'id': 4, 'Year': 1977, 'Title': 'Rage', 'handle': 'rage', 'Publisher': 'Signet Books', 'ISBN': '978-0-451-07645-8', 'Pages': 211, 'Notes': ['Published under pseudonym Richard Bachman'], 'created_at': '2023-11-13T23:48:48.339Z', 'villains': []}, {'id': 5, 'Year': 1978, 'Title': 'The Stand', 'handle': 'the-stand', 'Publisher': 'Doubleday', 'ISBN': '978-0-385-12168-2', 'Pages': 823, 'Notes': ['Nominee, World Fantasy Award, 1979', 'Runner-up (15th place), Locus Award, 1979[2]'], 'created_at': '2023-11-13T23:48:48.477Z', 'villains': [{'name': 'Donald Merwin Elbert', 'url': 'https://stephen-king-api.onrender.com/api/villain/34'}, {'name': 'Randall Flagg', 'url': 'https://stephen-king-api.onrender.com/api/villain/37'}, {'name': 'Lloyd Henreid', 'url': 'https://stephen-king-api.onrender.com/api/villain/51'}, {'name': 'The Kid', 'url': 'https://stephen-king-api.onrender.com/api/villain/62'}, {'name': 'Harold Lauder', 'url': 'https://stephen-king-api.onrender.com/api/villain/64'}, {'name': 'Rat Man', 'url': 'https://stephen-king-api.onrender.com/api/villain/87'}]}, {'id': 6, 'Year': 1979, 'Title': 'The Long Walk', 'handle': 'the-long-walk', 'Publisher': 'Signet Books', 'ISBN': '978-0-451-08754-6', 'Pages': 384, 'Notes': ['Published under pseudonym Richard Bachman'], 'created_at': '2023-11-13T23:48:48.608Z', 'villains': [{'name': 'Randall Flagg', 'url': 'https://stephen-king-api.onrender.com/api/villain/37'}, {'name': 'The Major', 'url': 'https://stephen-king-api.onrender.com/api/villain/70'}]}, {'id': 7, 'Year': 1979, 'Title': 'The Dead Zone', 'handle': 'the-dead-zone', 'Publisher': 'Viking Press', 'ISBN': '978-0-670-26077-5', 'Pages': 428, 'Notes': ['Runner-up (2nd place), Locus Award for Best Fantasy Novel, 1980[2]'], 'created_at': '2023-11-13T23:48:48.753Z', 'villains': [{'name': 'Frank Dodd', 'url': 'https://stephen-king-api.onrender.com/api/villain/29'}, {'name': 'Henrietta Dodd', 'url': 'https://stephen-king-api.onrender.com/api/villain/30'}, {'name': 'Malcolm Janus', 'url': 'https://stephen-king-api.onrender.com/api/villain/71'}, {'name': 'Sonny Elliman', 'url': 'https://stephen-king-api.onrender.com/api/villain/93'}, {'name': 'Greg Stillson', 'url': 'https://stephen-king-api.onrender.com/api/villain/97'}, {'name': "The Devil's Dozen", 'url': 'https://stephen-king-api.onrender.com/api/villain/100'}]}, {'id': 8, 'Year': 1980, 'Title': 'Firestarter', 'handle': 'firestarter', 'Publisher': 'Viking Press', 'ISBN': '978-0-670-31541-3', 'Pages': 426, 'Notes': ['Nominee, British Fantasy Award’s August Derleth Award, 1981', 'Runner-up (8th place), Locus Award for Best Science Fiction Novel, 1981[2]'], 'created_at': '2023-11-13T23:48:48.876Z', 'villains': [{'name': 'James Hollister', 'url': 'https://stephen-king-api.onrender.com/api/villain/54'}, {'name': 'Charlie McGee', 'url': 'https://stephen-king-api.onrender.com/api/villain/73'}, {'name': 'John Rainbird', 'url': 'https://stephen-king-api.onrender.com/api/villain/86'}]}, {'id': 9, 'Year': 1981, 'Title': 'Roadwork', 'handle': 'roadwork', 'Publisher': 'Signet Books', 'ISBN': '978-0-451-09668-5', 'Pages': 274, 'Notes': ['Published under pseudonym Richard Bachman'], 'created_at': '2023-11-13T23:48:49.005Z', 'villains': []}, {'id': 10, 'Year': 1981, 'Title': 'Cujo', 'handle': 'cujo', 'Publisher': 'Viking Press', 'ISBN': '978-0-670-45193-7', 'Pages': 319, 'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1982', 'Runner-up (21st place), Locus Award for Best Fantasy Novel, 1982[2]'], 'created_at': '2023-11-13T23:48:49.131Z', 'villains': [{'name': 'Cujo', 'url': 'https://stephen-king-api.onrender.com/api/villain/19'}]}, {'id': 11, 'Year': 1982, 'Title': 'The Running Man', 'handle': 'the-running-man', 'Publisher': 'Signet Books', 'ISBN': '978-0-451-11508-9', 'Pages': 219, 'Notes': ['Published under pseudonym Richard Bachman'], 'created_at': '2023-11-13T23:48:49.252Z', 'villains': [{'name': 'The Gladiators', 'url': 'https://stephen-king-api.onrender.com/api/villain/42'}, {'name': 'Damon Killian', 'url': 'https://stephen-king-api.onrender.com/api/villain/63'}]}, {'id': 12, 'Year': 1982, 'Title': 'The Dark Tower: The Gunslinger', 'handle': 'the-dark-tower-the-gunslinger', 'Publisher': 'Grant', 'ISBN': '978-0-937986-50-9', 'Pages': 224, 'Notes': [''], 'created_at': '2023-11-13T23:48:49.374Z', 'villains': [{'name': 'Marten Broadcloak', 'url': 'https://stephen-king-api.onrender.com/api/villain/10'}, {'name': 'Crimson King', 'url': 'https://stephen-king-api.onrender.com/api/villain/17'}, {'name': 'Randall Flagg', 'url': 'https://stephen-king-api.onrender.com/api/villain/37'}, {'name': 'Sylvia Pittston', 'url': 'https://stephen-king-api.onrender.com/api/villain/84'}]}, {'id': 13, 'Year': 1983, 'Title': 'Christine', 'handle': 'christine', 'Publisher': 'Viking', 'ISBN': '978-0-670-22026-7', 'Pages': 526, 'Notes': ['Runner-up (6th place), Locus Award for Best Fantasy Novel, 1984[2]'], 'created_at': '2023-11-13T23:48:49.505Z', 'villains': [{'name': 'Christine (car)', 'url': 'https://stephen-king-api.onrender.com/api/villain/11'}, {'name': 'Arnie Cunningham', 'url': 'https://stephen-king-api.onrender.com/api/villain/20'}]}, {'id': 14, 'Year': 1983, 'Title': 'Pet Sematary', 'handle': 'pet-sematary', 'Publisher': 'Doubleday', 'ISBN': '978-0-385-18244-7', 'Pages': 374, 'Notes': ['Nominee, World Fantasy Award, 1984', 'Runner-up (7th place), Locus Award for Best Fantasy Novel, 1984[2]'], 'created_at': '2023-11-13T23:48:49.637Z', 'villains': [{'name': 'Winston Church', 'url': 'https://stephen-king-api.onrender.com/api/villain/13'}, {'name': 'Gage Creed', 'url': 'https://stephen-king-api.onrender.com/api/villain/15'}, {'name': 'Victor Pascow', 'url': 'https://stephen-king-api.onrender.com/api/villain/83'}, {'name': 'Wendigo', 'url': 'https://stephen-king-api.onrender.com/api/villain/110'}]}, {'id': 15, 'Year': 1983, 'Title': 'Cycle of the Werewolf', 'handle': 'cycle-of-the-werewolf', 'Publisher': 'Land of Enchantment', 'ISBN': '978-0-960-38282-8', 'Pages': 127, 'Notes': ['Illustrated by Bernie Wrightson'], 'created_at': '2023-11-13T23:48:49.757Z', 'villains': [{'name': 'Lester Lowe', 'url': 'https://stephen-king-api.onrender.com/api/villain/68'}]}, {'id': 16, 'Year': 1984, 'Title': 'The Talisman', 'handle': 'the-talisman', 'Publisher': 'Viking', 'ISBN': '978-0-670-69199-9', 'Pages': 646, 'Notes': ['Written with Peter Straub', 'Nominee, World Fantasy Award, 1985', 'Runner-up (4th place), Locus Award for Best Fantasy Novel, 1985[2]'], 'created_at': '2023-11-13T23:48:49.872Z', 'villains': []}, {'id': 17, 'Year': 1984, 'Title': 'The Eyes of the Dragon', 'handle': 'the-eyes-of-the-dragon', 'Publisher': 'Philtrum Press (1984)Viking (1987)', 'ISBN': '978-0-670-81458-9', 'Pages': 326, 'Notes': ['First published as a limited edition in 1984, then for the mass market in 1987'], 'created_at': '2023-11-13T23:48:49.988Z', 'villains': [{'name': 'Randall Flagg', 'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]}, {'id': 18, 'Year': 1984, 'Title': 'Thinner', 'handle': 'thinner', 'Publisher': 'NAL', 'ISBN': '978-0-453-00468-8', 'Pages': 309, 'Notes': ['Published under pseudonym Richard Bachman'], 'created_at': '2023-11-13T23:48:50.102Z', 'villains': []}, {'id': 19, 'Year': 1986, 'Title': 'It', 'handle': 'it', 'Publisher': 'Viking', 'ISBN': '978-0-670-81302-5', 'Pages': 1138, 'Notes': ['Winner, British Fantasy Award’s August Derleth Award, 1987', 'Nominee, World Fantasy Award, 1987', 'Runner-up (3rd place), Locus Award for Best Fantasy Novel, 1987[2]'], 'created_at': '2023-11-13T23:48:50.223Z', 'villains': [{'name': 'Henry Bowers', 'url': 'https://stephen-king-api.onrender.com/api/villain/7'}, {'name': 'Butch Bowers', 'url': 'https://stephen-king-api.onrender.com/api/villain/8'}, {'name': 'Greta Bowie', 'url': 'https://stephen-king-api.onrender.com/api/villain/9'}, {'name': 'Victor Criss', 'url': 'https://stephen-king-api.onrender.com/api/villain/18'}, {'name': 'Marcia Fadden', 'url': 'https://stephen-king-api.onrender.com/api/villain/35'}, {'name': 'John Garton', 'url': 'https://stephen-king-api.onrender.com/api/villain/39'}, {'name': 'Peter Gordon', 'url': 'https://stephen-king-api.onrender.com/api/villain/43'}, {'name': 'Patrick Hockstetter', 'url': 'https://stephen-king-api.onrender.com/api/villain/53'}, {'name': 'Belch Huggins', 'url': 'https://stephen-king-api.onrender.com/api/villain/55'}, {'name': 'It (Creature)', 'url': 'https://stephen-king-api.onrender.com/api/villain/57'}, {'name': 'Richard P. Macklin', 'url': 'https://stephen-king-api.onrender.com/api/villain/69'}, {'name': 'Alvin Marsh', 'url': 'https://stephen-king-api.onrender.com/api/villain/72'}, {'name': 'Sally Mueller', 'url': 'https://stephen-king-api.onrender.com/api/villain/79'}, {'name': 'Tom Rogan', 'url': 'https://stephen-king-api.onrender.com/api/villain/91'}, {'name': 'Christopher Unwin', 'url': 'https://stephen-king-api.onrender.com/api/villain/107'}]}, {'id': 20, 'Year': 1987, 'Title': 'The Dark Tower II: The Drawing of the Three', 'handle': 'the-dark-tower-ii-the-drawing-of-the-three', 'Publisher': 'Grant', 'ISBN': '978-0-937986-90-5', 'Pages': 400, 'Notes': ['Runner-up (16th place), Locus Award for Best Fantasy Novel, 1988[2]'], 'created_at': '2023-11-13T23:48:50.339Z', 'villains': [{'name': 'Jack Mort', 'url': 'https://stephen-king-api.onrender.com/api/villain/76'}]}, {'id': 21, 'Year': 1987, 'Title': 'Misery', 'handle': 'misery', 'Publisher': 'Viking', 'ISBN': '978-0-670-81364-3', 'Pages': 310, 'Notes': ['Winner, Bram Stoker Award, 1988', 'Nominee, World Fantasy Award, 1988[2]'], 'created_at': '2023-11-13T23:48:50.459Z', 'villains': [{'name': 'Annie Wilkes', 'url': 'https://stephen-king-api.onrender.com/api/villain/114'}]}, {'id': 22, 'Year': 1987, 'Title': 'The Tommyknockers', 'handle': 'the-tommyknockers', 'Publisher': 'Putnam', 'ISBN': '978-0-399-13314-5', 'Pages': 558, 'Notes': ['Runner-up (16th place), Locus Award for Best Science Fiction Novel, 1988[2]'], 'created_at': '2023-11-13T23:48:50.579Z', 'villains': [{'name': 'Tommyknockers', 'url': 'https://stephen-king-api.onrender.com/api/villain/104'}]}, {'id': 23, 'Year': 1989, 'Title': 'The Dark Half', 'handle': 'the-dark-half', 'Publisher': 'Viking', 'ISBN': '978-0-670-82982-8', 'Pages': 431, 'Notes': ['Runner-up (2nd place), Locus Award for Best Horror Novel, 1990[2]'], 'created_at': '2023-11-13T23:48:50.696Z', 'villains': [{'name': 'George Stark', 'url': 'https://stephen-king-api.onrender.com/api/villain/96'}]}, {'id': 24, 'Year': 1990, 'Title': 'The Stand Uncut', 'handle': 'the-stand-uncut', 'Publisher': 'Doubleday', 'ISBN': '978-0-385-19957-5', 'Pages': 1152, 'Notes': ['The Complete & Uncut Edition', "Runner-up (2nd place), Locus Award's Best Horror/Dark Fantasy Novel, 1991[2]"], 'created_at': '2023-11-13T23:48:50.809Z', 'villains': []}, {'id': 25, 'Year': 1991, 'Title': 'The Dark Tower III: The Waste Lands', 'handle': 'the-dark-tower-iii-the-waste-lands', 'Publisher': 'Grant', 'ISBN': '978-0-937986-17-2', 'Pages': 512, 'Notes': ['Nominee, Bram Stoker Award, 1992', 'Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'], 'created_at': '2023-11-13T23:48:50.926Z', 'villains': [{'name': 'Blaine the Mono', 'url': 'https://stephen-king-api.onrender.com/api/villain/3'}, {'name': 'Randall Flagg', 'url': 'https://stephen-king-api.onrender.com/api/villain/37'}]}, {'id': 26, 'Year': 1991, 'Title': 'Needful Things', 'handle': 'needful-things', 'Publisher': 'Viking', 'ISBN': '978-0-670-83953-7', 'Pages': 690, 'Notes': ['Nominee, Bram Stoker Award, 1992', 'Runner-up (13th place), Locus Award for Best Horror/Dark Fantasy Novel, 1992[2]'], 'created_at': '2023-11-13T23:48:51.044Z', 'villains': [{'name': 'Leland Gaunt', 'url': 'https://stephen-king-api.onrender.com/api/villain/40'}]}, {'id': 27, 'Year': 1992, 'Title': "Gerald's Game", 'handle': 'gerald-s-game', 'Publisher': 'Viking', 'ISBN': '978-0-670-84650-4', 'Pages': 352, 'Notes': [], 'created_at': '2023-11-13T23:48:51.165Z', 'villains': [{'name': 'Gerald Burlingame', 'url': 'https://stephen-king-api.onrender.com/api/villain/41'}, {'name': 'Raymond Andrew Joubert', 'url': 'https://stephen-king-api.onrender.com/api/villain/61'}, {'name': 'Tom Mahout', 'url': 'https://stephen-king-api.onrender.com/api/villain/103'}]}, {'id': 28, 'Year': 1992, 'Title': 'Dolores Claiborne', 'handle': 'dolores-claiborne', 'Publisher': 'Viking', 'ISBN': '978-0-670-84452-4', 'Pages': 305, 'Notes': ['Runner-up (14th place), Locus Award for Best Horror/Dark Fantasy Novel, 1993[2]'], 'created_at': '2023-11-13T23:48:51.295Z', 'villains': [{'name': 'Joe St. George', 'url': 'https://stephen-king-api.onrender.com/api/villain/95'}]}, {'id': 29, 'Year': 1994, 'Title': 'Insomnia', 'handle': 'insomnia', 'Publisher': 'Viking', 'ISBN': '978-0-670-85503-2', 'Pages': 787, 'Notes': ['Nominee, Bram Stoker Award, 1995', 'Runner-up (3rd place), Locus Award for Best Fantasy/Horror Novel, 1995[2]'], 'created_at': '2023-11-13T23:48:51.415Z', 'villains': [{'name': 'Crimson King', 'url': 'https://stephen-king-api.onrender.com/api/villain/17'}, {'name': 'Susan Day', 'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]}, {'id': 30, 'Year': 1995, 'Title': 'Rose Madder', 'handle': 'rose-madder', 'Publisher': 'Viking', 'ISBN': '978-0-670-85869-9', 'Pages': 420, 'Notes': ['Runner-up (3rd place), Locus Award for Best Horror/Dark Fantasy Novel, 1995[2]'], 'created_at': '2023-11-13T23:48:51.533Z', 'villains': [{'name': 'Norman Daniels', 'url': 'https://stephen-king-api.onrender.com/api/villain/22'}, {'name': 'Susan Day', 'url': 'https://stephen-king-api.onrender.com/api/villain/23'}]}, {'id': 31, 'Year': 1996, 'Title': 'The Green Mile', 'handle': 'the-green-mile', 'Publisher': 'Signet Books', 'ISBN': '978-0-451-19049-9978-0-451-19052-9978-0-451-19054-3978-0-451-19055-0978-0-451-19056-7978-0-451-19057-4', 'Pages': 400, 'Notes': ['Winner, Bram Stoker Award, 1997', 'Runner-up (8th place), Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'], 'created_at': '2023-11-13T23:48:51.660Z', 'villains': [{'name': 'Percy Wetmore', 'url': 'https://stephen-king-api.onrender.com/api/villain/111'}, {'name': 'William Wharton', 'url': 'https://stephen-king-api.onrender.com/api/villain/112'}]}, {'id': 32, 'Year': 1996, 'Title': 'Desperation', 'handle': 'desperation', 'Publisher': 'Viking', 'ISBN': '978-0-670-86836-0', 'Pages': 704, 'Notes': ['Twin novel of The Regulators', 'Winner, Locus Award for Best Horror/Dark Fantasy Novel, 1997[2]'], 'created_at': '2023-11-13T23:48:51.784Z', 'villains': []}, {'id': 33, 'Year': 1996, 'Title': 'The Regulators', 'handle': 'the-regulators', 'Publisher': 'Dutton', 'ISBN': '978-0-525-94190-3', 'Pages': 480, 'Notes': ['Published under pseudonym Richard Bachman', 'Twin novel of Desperation'], 'created_at': '2023-11-13T23:48:51.900Z', 'villains': []}, {'id': 34, 'Year': 1997, 'Title': 'The Dark Tower IV: Wizard and Glass', 'handle': 'the-dark-tower-iv-wizard-and-glass', 'Publisher': 'Grant', 'ISBN': '978-1-880418-38-3', 'Pages': 787, 'Notes': ['Runner-up (4th place), Locus Award for Best Fantasy Novel, 1998', 'Runner-up (6th place), Locus Award for Best Art Book, 1998[2]'], 'created_at': '2023-11-13T23:48:52.019Z', 'villains': [{'name': 'Blaine the Mono', 'url': 'https://stephen-king-api.onrender.com/api/villain/3'}, {'name': 'Cordelia Delgado', 'url': 'https://stephen-king-api.onrender.com/api/villain/24'}, {'name': 'Rhea Dubativo', 'url': 'https://stephen-king-api.onrender.com/api/villain/32'}, {'name': 'John Farson', 'url': 'https://stephen-king-api.onrender.com/api/villain/36'}, {'name': 'Randall Flagg', 'url': 'https://stephen-king-api.onrender.com/api/villain/37'}, {'name': 'Eldred Jonas', 'url': 'https://stephen-king-api.onrender.com/api/villain/60'}]}, {'id': 35, 'Year': 1998, 'Title': 'Bag of Bones', 'handle': 'bag-of-bones', 'Publisher': 'Scribner', 'ISBN': '978-0-684-85350-5', 'Pages': 529, 'Notes': ['Winner, Bram Stoker Award, 1999', 'Winner, British Fantasy Award’s August Derleth Award, 1999', 'Winner, Locus Award for Best Dark Fantasy/Horror Novel, 1999[2]'], 'created_at': '2023-11-13T23:48:52.137Z', 'villains': []}, {'id': 36, 'Year': 1999, 'Title': 'The Girl Who Loved Tom Gordon', 'handle': 'the-girl-who-loved-tom-gordon', 'Publisher': 'Scribner', 'ISBN': '978-0-684-86762-5', 'Pages': 224, 'Notes': [], 'created_at': '2023-11-13T23:48:52.251Z', 'villains': []}, {'id': 37, 'Year': 2001, 'Title': 'Dreamcatcher', 'handle': 'dreamcatcher', 'Publisher': 'Scribner', 'ISBN': '978-0-743-21138-3', 'Pages': 620, 'Notes': [], 'created_at': '2023-11-13T23:48:52.368Z', 'villains': []}, {'id': 38, 'Year': 2001, 'Title': 'Black House', 'handle': 'black-house', 'Publisher': 'Random House', 'ISBN': '978-0-375-50439-6', 'Pages': 625, 'Notes': ['Sequel to The Talisman', 'Written with Peter Straub', 'Nominee, Bram Stoker Award, 2002', 'Runner-up (7th place), Locus Award for Best Fantasy Novel, 2002[2]'], 'created_at': '2023-11-13T23:48:52.483Z', 'villains': [{'name': 'Crimson King', 'url': 'https://stephen-king-api.onrender.com/api/villain/17'}]}, {'id': 39, 'Year': 2002, 'Title': 'From a Buick 8', 'handle': 'from-a-buick-8', 'Publisher': 'Scribner', 'ISBN': '978-0-743-21137-6', 'Pages': 368, 'Notes': ['Nominee, Bram Stoke

,id,Year,Title,handle,Publisher,ISBN,Pages,Notes,created_at,villains
0,1,1974,Carrie,carrie,Doubleday,978-0-385-08695-0,199,[],2023-11-13T23:48:47.848Z,"[{'name': 'Tina Blake', 'url': 'https://stephe..."
1,2,1975,Salem's Lot,salem-s-lot,Doubleday,978-0-385-00751-1,439,"[Nominee, World Fantasy Award, 1976[2]]",2023-11-13T23:48:48.098Z,"[{'name': 'Kurt Barlow', 'url': 'https://steph..."
2,3,1977,The Shining,the-shining,Doubleday,978-0-385-12167-5,447,"[Runner-up (4th place), Locus Award for Best F...",2023-11-13T23:48:48.219Z,"[{'name': 'Horace M. Derwent', 'url': 'https:/..."
3,4,1977,Rage,rage,Signet Books,978-0-451-07645-8,211,[Published under pseudonym Richard Bachman],2023-11-13T23:48:48.339Z,[]
4,5,1978,The Stand,the-stand,Doubleday,978-0-385-12168-2,823,"[Nominee, World Fantasy Award, 1979, Runner-up...",2023-11-13T23:48:48.477Z,"[{'name': 'Donald Merwin Elbert', 'url': 'http..."
...,...,...,...,...,...,...,...,...,...,...
58,59,2018,The Outsider,the-outsider,Scribner,978-1-50118-098-9,576,"[First novel in the Holly Gibney Series, Runne...",2023-11-13T23:48:55.165Z,"[{'name': 'The Outsider (Creature)', 'url': 'h..."
59,60,2018,Elevation,elevation,Scribner,978-1-98210-231-9,144,[],2023-11-13T23:48:55.291Z,[]
60,61,2019,The Institute,the-institute,Scribner,978-1-98211-056-7,576,"[Nominee, British Fantasy Award's August Derle...",2023-11-13T23:48:55.457Z,"[{'name': 'Gladys Hickson', 'url': 'https://st..."
61,62,2021,Later,later,Hard Case Crime,978-1-78909-649-1,256,[],2023-11-13T23:48:55.579Z,[]
62,63,2021,Billy Summers,billy-summers,Scribner,978-1-982-17361-6,528,[],2023-11-13T23:48:55.753Z,[]

In [22]:
# web scrapping
import requests
for i in range(100000):
 res=requests.get("https://www.scrapethissite.com/pages/simple/")
print(res)

# import beautifulsoup4 as bs4

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

In [14]:
! pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (4.15.0)

In [27]:
f=open("1.html","r")
# f.write(res.text)
html_content=f.read()
f.close

In [28]:
from bs4 import BeautifulSoup
# from mistune import lxml

soup=BeautifulSoup(html_content,"lxml")

In [ ]:
all_h3=soup.find_all("h3")
for h3 in all_h3:
 print(h3.get_text(strip=True))

Andorra
United Arab Emirates
Afghanistan
Antigua and Barbuda
Anguilla
Albania
Armenia
Angola
Antarctica
Argentina
American Samoa
Austria
Australia
Aruba
Åland
Azerbaijan
Bosnia and Herzegovina
Barbados
Bangladesh
Belgium
Burkina Faso
Bulgaria
Bahrain
Burundi
Benin
Saint Barthélemy
Bermuda
Brunei
Bolivia
Bonaire
Brazil
Bahamas
Bhutan
Bouvet Island
Botswana
Belarus
Belize
Canada
Cocos [Keeling] Islands
Democratic Republic of the Congo
Central African Republic
Republic of the Congo
Switzerland
Ivory Coast
Cook Islands
Chile
Cameroon
China
Colombia
Costa Rica
Cuba
Cape Verde
Curacao
Christmas Island
Cyprus
Czech Republic
Germany
Djibouti
Denmark
Dominica
Dominican Republic
Algeria
Ecuador
Estonia
Egypt
Western Sahara
Eritrea
Spain
Ethiopia
Finland
Fiji
Falkland Islands
Micronesia
Faroe Islands
France
Gabon
United Kingdom
Grenada
Georgia
French Guiana
Guernsey
Ghana
Gibraltar
Greenland
Gambia
Guinea
Guadeloupe
Equatorial Guinea
Greece
South Georgia and the South Sandwich Islands
Guatemala
Guam
Guinea-Bissau
Guyana
Hong Kong
Heard Island and McDonald Islands
Honduras
Croatia
Haiti
Hungary
Indonesia
Ireland
Israel
Isle of Man
India
British Indian Ocean Territory
Iraq
Iran
Iceland
Italy
Jersey
Jamaica
Jordan
Japan
Kenya
Kyrgyzstan
Cambodia
Kiribati
Comoros
Saint Kitts and Nevis
North Korea
South Korea
Kuwait
Cayman Islands
Kazakhstan
Laos
Lebanon
Saint Lucia
Liechtenstein
Sri Lanka
Liberia
Lesotho
Lithuania
Luxembourg
Latvia
Libya
Morocco
Monaco
Moldova
Montenegro
Saint Martin
Madagascar
Marshall Islands
Macedonia
Mali
Myanmar [Burma]
Mongolia
Macao
Northern Mariana Islands
Martinique
Mauritania
Montserrat
Malta
Mauritius
Maldives
Malawi
Mexico
Malaysia
Mozambique
Namibia
New Caledonia
Niger
Norfolk Island
Nigeria
Nicaragua
Netherlands
Norway
Nepal
Nauru
Niue
New Zealand
Oman
Panama
Peru
French Polynesia
Papua New Guinea
Philippines
Pakistan
Poland
Saint Pierre and Miquelon
Pitcairn Islands
Puerto Rico
Palestine
Portugal
Palau
Paraguay
Qatar
Réunion
Romania
Serbia
Russia
Rwanda
Saudi Arabia
Solomon Islands
Seychelles
Sudan
Sweden
Singapore
Saint Helena
Slovenia
Svalbard and Jan Mayen
Slovakia
Sierra Leone
San Marino
Senegal
Somalia
Suriname
South Sudan
São Tomé and Príncipe
El Salvador
Sint Maarten
Syria
Swaziland
Turks and Caicos Islands
Chad
French Southern Territories
Togo
Thailand
Tajikistan
Tokelau
East Timor
Turkmenistan
Tunisia
Tonga
Turkey
Trinidad and Tobago
Tuvalu
Taiwan
Tanzania
Ukraine
Uganda
U.S. Minor Outlying Islands
United States
Uruguay
Uzbekistan
Vatican City
Saint Vincent and the Grenadines
Venezuela
British Virgin Islands
U.S. Virgin Islands
Vietnam
Vanuatu
Wallis and Futuna
Samoa
Kosovo
Yemen
Mayotte
South Africa
Zambia
Zimbabwe

In [ ]:
all_populations=soup.find_all("span", class_="country-population")
for population in all_populations:
 print(population.get_text(strip=True))
 all_countries=soup.find_all("span", class_="country-name")

84000
4975593
29121286
86754
13254
2986952
2968000
13068161
0
41343201
57881
8205000
21515754
71566
26711
8303512
4590000
285653
156118464
10403000
16241811
7148785
738004
9863117
9056010
8450
65365
395027
9947418
18012
201103330
301790
699847
0
2029307
9685000
314522
33679000
628
70916439
4844927
3039126
7581000
21058798
21388
16746491
19294149
1330044000
47790000
4516220
11423000
508659
141766
1500
1102677
10476000
81802257
740528
5484000
72813
9823821
34586184
14790608
1291170
80471869
273008
5792984
46505963
88013491
5244000
875983
2638
107708
48228
64768389
1545255
62348447
107818
4630000
195506
65228
24339838
27884
56375
1593256
10324025
443000
1014999
11000000
30
13550440
159358
1565126
748486
6898686
0
7989415
4491000
9648924
9982000
242968342
4622917
7353985
75049
1173108018
4000
29671605
76923300
308910
60340328
90812
2847232
6407085
127288000
40046566
5776500
14453680
92533
773407
51134
22912177
48422644
2789132
44270
15340000
6368162
4125247
160922
35000
21513990
3685076
1919552
2944459
497538
2217969
6461454
31627428
32965
4324000
666730
35925
21281844
65859
2062294
13796354
53414374
3086918
449198
53883
432900
3205060
9341
403000
1294104
395650
15447500
112468855
28274729
22061451
2128471
216494
15878271
1828
154000000
5995928
16645000
5009150
28951852
10065
2166
4252277
2967717
3410676
29907003
270485
6064515
99900177
184404791
38500000
7012
46
3916632
3800000
10676000
19907
6375830
840926
776948
21959278
7344847
140702000
11055976
25731776
559198
88340
35000000
9828655
4701069
7460
2007000
2550
5455000
5245695
31477
12323252
10112453
492829
8260490
175808
6052064
37429
22198110
1354051
20556
10543464
140
6587239
67089500
7487489
1466
1154625
4940916
10589025
122580
77804122
1228691
10472
22894384
41892895
45415596
33398682
0
310232863
3477000
27865738
921
104217
27223228
21730
108708
89571130
221552
16025
192001
1800000
23495361
159042
49000000
13460305
11651858

In [ ]:
pd.DataFrame(columns=["country","population"])

Empty DataFrame
Columns: [country, population]
Index: []